# Generated by Django 6.0.1 on 2026-03-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Auto-filled image URL (used when no file is uploaded)'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='tours/thumbnails/'),
        ),
    ]
